bold="\033[1m"
reset="\033[0m"
black="\033[30m"
italic="\033[31m"
highlight="\033[107m\033[30m"
end="\033[0m"
red="\033[31m"

print("═════════════════════════════════════════════════════════════════════════════════════════════════════════════════")
print((bold+"RESUME").center(110))
print("═════════════════════════════════════════════════════════════════════════════════════════════════════════════════")
print(highlight+" OBJECTIVES: " + end)
print(bold+"•To be a successful and skilled computer engineer that contribute to he continuous innovation of modern")
print(bold+" technology.")
print("═════════════════════════════════════════════════════════════════════════════════════════════════════════════════")
print( highlight+ " PERSONAL BACKGROUND:"+end)
name=input((bold+"Name (Surname, First Name, Middle I.:)").center(30))
sex=input((bold+"Male/Female:").center(40))
birthday=input((bold+"Birthdate (MM/DD/YY):").center(40))
age=input((bold+"Age (Years):").center(40))
address=input((bold+"Address:").center(40))
civilstatus=input((bold+"Civil Status:").center(40))
nationality=input((bold+"Nationality:").center(40))
religion=input((bold+"Religion:").center(40))
email=input((bold+"Personal Email:").center(40))
print("═════════════════════════════════════════════════════════════════════════════════════════════════════════════════")
print( highlight+ " EDUCATIONAL BACKGROUND:"+end)
elementary=input((bold+">Elementary School (YEAR):").center(40))
juniors=input((bold+">Junior High School (YEAR):").center(40))
senior=input((bold+">Senior High School / STRAND(YEAR):").center(40))
college=input((bold+">College Education / COURSE (YEAR):").center(40))
print("═════════════════════════════════════════════════════════════════════════════════════════════════════════════════")
print( highlight+ " SKILLS:"+end)
print(reset+"•Programming")
print(reset+"•Communication Skills")
print(reset+"•Creativity in Project Design")
print(reset+"•Critical Thinker")
print("═════════════════════════════════════════════════════════════════════════════════════════════════════════════════")
print( highlight+ " ACHIEVEMENTS "+end)
achievements=input(bold+"My Achievements:")
print("•Junior High School Graduate (WITH HONORS)")
print("•Grade 11 (WITH HONORS)")
print("•Grade 12 / 1st Semester (WITH HONORS)")
print("•Grade 12 / 2nd Semester (WITH HIGH HONORS)")
print("•Grade 11 and 12 Captain of Men's Volleyball Team (VARSITY/ATHLETE)")
print("•SISAC Inter-School Volleyball League (BRONZE MEDALIST)")
print("•Grade 11 Intramurals (SILVER MEDALIST)")
print("•Grade 12 Intramurals (BRONZE MEDALIST)")
print("•2025 Intramurals / Grade 12 (MYTHICAL 6)")
print("═════════════════════════════════════════════════════════════════════════════════════════════════════════════════")
print( highlight+ " CHARACTER REFERENCE "+end)
Name=input(bold+"Name:")
title=input(bold+"Title:")
contact=input(bold+"Contact Number:")
print("═════════════════════════════════════════════════════════════════════════════════════════════════════════════════")