print("                             \033[1mRESUME")
print(" ╔═══════════════════════════════════════════════════════════╦═════════════════╗               ")
print(" ║                                                           ║                 ║               ")
print(" ║ \033[1mBONCAY,JOSE BENEDICT L.                                   ║     2x2 ID      ║               ")
print(" ║ \033[0mCamia St, Brgy. San Isidro, Cainta, Rizal                 ║     PICTURE     ║               ")
print(" ║ 09516985217                                               ║                 ║               ")
print(" ║ \033[1mEmail Address: \033[0mjbboncay1@gmail.com                        ║                 ║               ")
print(" ║                                                           ╚═════════════════║               ")
print(" ║⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯║               ")
print(" ║ \033[1;4mOBJECTIVE:\033[0m                                                                  ║               ")
print(" ║ • \033[1mTo be a successful and skilled computer engineer that contribute to the   ║               ")
print(" ║   continuous innovation of modern technology.                               ║               ")
print(" ║                                                                             ║               ")
print(" ║ \033[1;4mPERSONAL BACKGROUND:\033[0m                                   \033[1;4mSKILLS:\033[0m              ║                 ")
print(" ║ \033[1mNAME(Surname, First Name, Middle I.):\033[0m                 •Programming          ║                  ")
print(" ║      \033[0mBoncay, Jose Benedict L.                         •Communication Skills ║               ")
print(" ║ \033[1mSEX:\033[0mMale                                              •Creativity in        ║               ")
print(" ║ \033[1mBIRTHDAY/AGE: \033[0mJuly 17, 2007 / 18yrs old                Project Designs      ║               ")
print(" ║ \033[1mBIRTHPLACE: \033[0mTabaco City, Albay                        •Critical Thinker     ║               ")
print(" ║ \033[1mCIVIL STATUS:\033[0mSingle                                                         ║               ")
print(" ║ \033[1mNATIONALITY:\033[0mFilipino                                                        ║               ")
print(" ║ \033[1mRELIGION: \033[0mRoman Catholic                                                    ║               ")
print(" ║                                                                             ║               ")
print(" ║ \033[1;4mEDUCATIONAL BACKGROUND:\033[0m                                                     ║              ")
print(" ║  >\033[1mSENIOR HIGH SCHOOL(YEAR): \033[0mSTI College Cubao(2023-2025)                    ║               ")
print(" ║  >\033[1mJUNIOR HIGH SCHOOL(YEAR):\033[0mJose P. Laurel Sr. High School(2018-2023)        ║               ")
print(" ║  >\033[1mELEMENTARY(YEAR):\033[0mTeodora Alonzo Elementary School(2013-2018)              ║               ")
print(" ║                                                                             ║               ")
print(" ║ \033[1;4mACHIEVEMENTS:\033[0m                                                               ║               ")
print(" ║ •\033[0mJunior High School Graduate (\033[1mWITH HONORS)                                  ║               ")
print(" ║ •\033[0mGrade 11(\033[1mWITH HONORS)                                                      ║               ")
print(" ║ •\033[0mGrade 12 / 1st Semester (\033[1mWITH HONORS)                                      ║               ")
print(" ║ •\033[0mGrade 12 / 2nd Semester (\033[1mWITH HIGH HONORS)                                 ║               ")
print(" ║ •\033[0mGrade 11 and 12 Captain of Men's Volleyball Team (\033[1mVARSITY)                 ║               ")
print(" ║ •\033[0mSISAC Inter-School Volleyball League (\033[1mBRONZE MEDALIST)                     ║               ")
print(" ║ •\033[0mGrade 11 Intramurals (\033[1mSILVER MEDALIST)                                     ║               ")
print(" ║ •\033[0mGrade 12 Intramurals (\033[1mBRONZE MEDALIST)                                     ║               ")
print(" ║ •\033[0m2025 Intramurals (\033[1mMYTHICAL 5)                                              ║               ")
print(" ║                                                                             ║               ")
print(" ║ \033[1;4mCHARACTER REFERENCES:\033[0m                                                       ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ║                                                                             ║               ")
print(" ╚═════════════════════════════════════════════════════════════════════════════╝               ")







